### ISSUE TITLE
Rate limit exceeded error

### ISSUE THREAD

**Issue by otsukaresamurai** [vrickey123/LeapForWaniKani#35]
I get this JSON error very frequently when trying to do reviews: 

`{"error":"Rate limit exceeded","code":429}`

Tried disabling the VPN on my phone, no change. The API key I'm using for this app isn't used for any others. If I try a different WK app at the same time I don't get the error.

Spontaneously resolves after a while. It sometimes happens during a review session, too. First I get that message from WK that it's lost its connection and needs to refresh, then the error is shown.

**Comment by vrickey123** [comment]
@otsukaresamurai By any chance could you share more info on the step-by-step process you took to get that error and where you logged that error code? Since the reviews function of this app is handled wanikani.com in a webview - there aren't any review-related API calls made at that time - I would be surprised if the app caused the rate limit to be exceeded during reviews. While it's possible, the only two API calls we make are for a `Summary` and `Assignments`. To eliminate other factors, do you use any other third-party web extensions?

**Comment by otsukaresamurai** [comment]
It's just displayed directly in the browser, presumably as the GET or POST
request response. I initially assumed it was a WK issue since it's clear
you're just wrapping it via webview, but this issue only happens with this
app and not with an iOS app that works the same way.

The only thing on this device (Pixel 3) that could interfere is the VPN,
but the issue still happens with the VPN disabled.

**Comment by vrickey123** [comment]
Thanks for the details. I have never encountered it and you're the first to report it, but it may be legit in that case. The only two places that I think could cause the issue are in the Android Activity and Fragment Lifecycle onResume callback when we make a [request for a summary and assignments](https://github.com/vrickey123/LeapForWaniKani/blob/develop/app/src/main/java/com/leapsoftware/leapforwanikani/dashboard/DashboardFragment.kt#L120) or [user after you login](https://github.com/vrickey123/LeapForWaniKani/blob/develop/app/src/main/java/com/leapsoftware/leapforwanikani/MainActivity.kt#L78) with your API key or return from the webview back to the Dashboard. (I made a mistake in my previous comment. A `User` API call is also made by the app.)

**Comment by vrickey123** [comment]
I haven't had the chance to try and reproduce this, but if there is a bug in the wild, the most likely reason for exceeding the rate limite would be a Paged Assignment request. Back when this code was written, Coroutine support for Paged requests didn't exist, but it was added as part of Android 11 in September. There is an enhancement tracking that feature in #32

**Comment by otsukaresamurai** [comment]
I'm a little surprised I'm the only one reporting this so I'm concerned
that this is particular to me. To pursue a more general benefit, you might
consider checking whether the webview HTTP response is 200 and HTML vs.
some other code and not HTML so you can get some insight into which
requests are failing.

**Comment by otsukaresamurai** [comment]
I just saw this same error in another app so I don't think this is your
issue. Sorry for the trouble!
